- Resources/Views/docs-geocoding-api.leaf
I fixed a typo I recently discovered: `Floating ppint` -> `Floating point`
> [Fix] Typo docs-geocoding-api.leaf

- Resources/Views/docs.leaf
Fix typo 'Lisabon' on city options
> Typo in Lisbon city option

- Sources/App/Domains/Gridable.swift
```swift
/build/Sources/App/Domains/Gridable.swift:82:13: warning: variable 'elevation' was never mutated; consider changing to 'let' constant
var elevation = try readFromStaticFile(gridpoint: gridpoint, file: elevationFile)
~~~ ^
let
```
> Gridable: fix compiler warning

- Sources/App/Gfs/GfsController.swift
- Sources/App/Gfs/GfsDomain.swift
- Sources/App/Gfs/GfsDownload.swift
- Sources/App/Gfs/GfsVariableDownloadable.swift
- Sources/App/Helper/Array2DInterpolation.swift
- Sources/App/Helper/Meteorology.swift
- Sources/App/Helper/Time/Time.swift
- Sources/App/Icon/Icon.swift
- Sources/App/Icon/IconVariableDownloadable.swift
- Sources/App/configure.swift
- Sources/CTurboPFor/src/vsimple.c
This PR uses more surface variables from GFS013 instead of GFS025:
- Precipitation, showers and snow fall
- Surface level pressure -> pressure mean sea level is now calculated on demand in the API code
- Relative humidity calculated from specific humidity
- Vertical velocity (geometric) in m/s
Memory consumption of the GFS013 downloader code will be increased by 50 MB to keep temporary results in memory
see #259
> GFS: support for additional gfs013 variables

- Sources/App/MeteoFrance/MeteoFranceDownloader.swift
After 14. February Meteofrance arpege download for the 12z Europe run got very unreliable. It now takes up to 7 hours to download it, because the last files arrive very late
> Météo France a fait évoluer le 14 février 2023 les packages ARPEGE en téléchargement direct. Les échéances sont désormais limitées à 102h pour le modèle de 12h UTC.
https://donneespubliques.meteofrance.fr/?fond=produit&id_produit=130&id_rubrique=51
> On February 14, 2023, Météo France updated the ARPEGE packages for direct download. Deadlines are now limited to 102h for the 12h UTC model.
> Increase arpege download timeout

- Sources/App/Commands/CronjobCommand.swift
- Sources/App/Icon/DownloadIconCommand.swift
- Sources/App/Icon/Icon.swift
Use ICON-EU side runs with updates every 3 hours instead of 6 hourly updates. 6-hourly updates only offer 31 10-hourly values. 
Although 6 hourly time steps are available until +51 hours since initialisation, due to 6-hourly resolution they do not provide much benefit. Thus only 31 hours are used.
Using 3h sideburns, should improve current weather conditions as well as a better assimilated historical time-series. They will however make it more difficult for #206.
> Use ICON-EU side runs with updates every 3 hours

- Sources/App/MeteoFrance/MeteoFranceController.swift
- Sources/App/MeteoFrance/MeteoFranceDomain.swift
- Sources/App/MeteoFrance/MeteoFranceVariableDownloadable.swift
- Tests/AppTests/SwiftPFor2DTests.swift
This PR adds support for 20, 50, 100, 150 and 200 m above ground wind and temperature for MeteoFrance Arome and Arpege models.
AromeHD only include wind forecasts for level 20, 50 and 100 meters
> MeteoFrance: Add 20, 50, 100, 150 and 200 m above ground wind and temperature

- openapi.yml
I am one of the developers of the [Micronaut Framework](https://micronaut.io/). As part of writing a guide for our [OpenAPI support](https://github.com/micronaut-projects/micronaut-openapi/), I was contemplating using Open Meteo as an example service.
I was happy to find it was coming with an OpenAPI spec. However, the response types are not precise enough for our generated code. Typically, return types are often `Object` instead of something strongly typed.
This commit fixes this by introducing component types with the appropriate return types. I'm not an OpenAPI expert but I have verified that this fixes the issue I was seeing.
> Improve OpenAPI definition

- Sources/App/Dem/DownloadDem.swift
This PR modifies the `download-dem` command to process downloaded files concurrently using task groups. This significantly speeds up processing as the command can make use of multiple CPUs.
Feel free to change anything or let me know what should be updated, this is the first Swift code I've written. 😄
> Process download-dem files concurrently

- Sources/App/Gem/GemDownloader.swift
- Sources/App/Gfs/GfsDownload.swift
Increase deadLineHours for GEM and GFS model downloader, fix #428
> Increase deadLineHours for GEM and GFS model downloader

- docs/getting-started.md
This pull requets updates the `docs/getting-started.md` file, in which the documentation for "deployment" lifes in.
- Updated the link for ICON weather variables from [enum IconVariable](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Icon/Icon.swift#L173) to [IconVariables](https://github.com/open-meteo/open-meteo/blob/main/Sources/App/Icon/IconVariableDownloadable.swift#L84) in the `getting-started.md` file.
- Added installation command for the `awscli`, via `sudo apt-get install awscli`
The current link was leading to the wrong/ old file, causing confusion for users trying to access the list of ICON weather variables. This change ensures that the link accurately directs users to the correct location.
The Aws S3 Bucket Sync only works, if the `awscli` is installed.
> Change enum IconVariable and Awscli installation via APT - Update getting-started.md

- Sources/App/Helper/ForecastapiQuery.swift
Remove error if daily variables are used, but no timezone is specified. Instead a warning will be displayed in the API documentation
> Make timezones optional for daily data

- Package.resolved
- Package.swift
- Sources/App/Cmip6/CmipController.swift
- Sources/App/Controllers/EnsembleController.swift
- Sources/App/Controllers/ForecastapiController.swift
- Sources/App/Era5/CerraDomain.swift
- Sources/App/Era5/Era5Controller.swift
- Sources/App/Era5/Era5Domain.swift
- Sources/App/Gem/GemController.swift
- Sources/App/Gfs/GfsController.swift
- Sources/App/Helper/FlatBufferWriter/FlatBuffers+EnsembleApi.swift
- Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
- Sources/App/Helper/Zensun.swift
- Sources/App/Icon/IconController.swift
- Sources/App/Icon/IconReader.swift
- Sources/App/JMA/JmaController.swift
- Sources/App/MetNo/MetNoController.swift
- Sources/App/MeteoFrance/MeteoFranceController.swift
Add `daylight_duration` to daily variables. Calculation is based on sunrise/-set time.
Add `sunshine_duration` to hourly and daily variables. Calculation is based on DNI > 120. Because data is averaged over 1 hour. It is assuming a linear distribution between 60 and 180 watts. Sunrise and -set times are used to bound the available daylight.
> feat: Integrate daylight and sunshine duration

- Sources/App/Helper/Intrinsics/Concurrency.swift
- Sources/App/JMA/JmaDownloader.swift
- Sources/SwiftPFor2D/FileExtension.swift
- Sources/SwiftPFor2D/SwiftPFor2D.swift
A couple of weeks ago, overlapping JMA MSM runs seems to have occurred. This PR keeps file handles open to protect from overlapping runs
> Fix: Protect JMA downloader against overlapping runs

- Sources/App/Helper/WeatherCode.swift
- Sources/App/Icon/DownloadIconCommand.swift
ICON weather codes show drizzle or other forms of light precipitation even if precipitation is indicated as 0. This PR overwrites weather codes for precipitation = 0 events.
> fix: Correct DWD ICON weather codes to remove drizzle if precipitation is 0

- Sources/App/Cams/CamsDownload.swift
- Sources/App/Ecmwf/DownloadEcmwfCommand.swift
- Sources/App/Gfs/GfsDomain.swift
- Sources/App/Gfs/GfsDownload.swift
- Sources/App/Helper/Intrinsics/Sequence.swift
- Sources/App/Helper/Time/Time.swift
- Sources/App/Helper/Ulimit.swift
- Sources/App/Icon/DownloadIconCommand.swift
- Sources/App/JMA/JmaDownloader.swift
- Sources/App/MetNo/MetNoDownloader.swift
- Sources/App/MeteoFrance/MeteoFranceDownloader.swift
- Sources/App/SeasonalForecast/SeasonalForecastDownload.swift
GFS ensemble downloads may take longer than 6 hours resulting in overlapping runs. Because the downloaded files could be overwritten by the next downloader process, the previous downloader will be terminated.
Change downloader to keep file handles open, solving this issue and allow parallel downloads.
> Rework NCEP GFS downloader

- Sources/App/Bom/BomDomain.swift
For some reason my swift compiler failed without adding the `return`s in these switch/case statements.
My compiler is on Fedora 38 linux, on intel-i7 CPUs:
```swift --version
Swift version 5.8.1 (swift-5.8.1-RELEASE)
Target: x86_64-unknown-linux-gnu
```
> fix missing return keyword in switch case blocks

- Sources/App/Bom/BomDownloader.swift
- Sources/App/Helper/Download/Curl+Grib.swift
- Sources/App/Helper/Download/Curl+NetCDF.swift
- Sources/App/Helper/Download/Curl.swift
- Sources/App/Helper/Download/TimeoutTracker.swift
Downloaders like BOM may download files that are being uploaded at the same time. This results in corrupted files. Check integrity of downloaded NetCDF files and retry
> Check integrity of downloaded NetCDF files and retry corrupted files

- Sources/App/Gfs/GfsDownload.swift
- Sources/App/SeasonalForecast/SeasonalForecastDownload.swift
The `static` directory was not automatically generated, resulting in a write permission error
> fix: GFS/HRRR downloads in case `static` directory does not exist

- Sources/App/Cmip6/CmipDownloader.swift
- Sources/App/Commands/ExportCommand.swift
- Sources/App/Commands/SyncCommand.swift
- Sources/App/Domains/Gridable.swift
- Sources/App/Helper/OmFileManager.swift
- Sources/App/Helper/Reader/GenericDomain.swift
- Sources/App/configure.swift
- Sources/SwiftPFor2D/Backend.swift
- Sources/SwiftPFor2D/FileExtension.swift
- Sources/SwiftPFor2D/MmapFile.swift
- Sources/SwiftPFor2D/MmapFileCached.swift
- Sources/SwiftPFor2D/SwiftPFor2D.swift
- build/openmeteo-sync.service
Currently open-meteo archives use hybrid storage using ZFS with HDDs as large storage and SSDs as fast cache. This adds a lot of overhead and cannot be fine controlled. This PR adds a direct implementation for storage tiering. This is a bit experimental and uncertain if it works out.
> feat: Implement cache tier to use hybrid storage

- Sources/App/Controllers/ForecastapiController.swift
- Sources/App/Domains/GaussianGrid.swift
- Sources/App/Ecmwf/DownloadEcmwfCommand.swift
- Sources/App/Ecmwf/EcmwfDomain.swift
- Sources/App/Ecmwf/EcmwfReader.swift
- Sources/App/Ecmwf/EcmwfVariable.swift
- Sources/App/Helper/DomainRegistry.swift
- Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
Data available here: https://data.ecmwf.int/forecasts/20240228/06z/aifs/0p25/oper/. First ever open-data of AIFS.
Specs:
- 6 hourly data, 15 days forecast
- 0.25° Gaussian N320 grid
- Same variables as IFS025 (surface and pressure)
- Additional pressure level 100, 400 and 600 hPa
- Dew point on 2 metre now directly available
> Integrate AIFS from ECMWF

- Sources/App/Controllers/ForecastapiController.swift
The old 0.4° will be shut down in the near future and does not provide all variables like solar radiation
> fix: switch /v1/ecmwf api endpoint to ifs025 version as default model

- Sources/App/Controllers/ForecastapiController.swift
Sun rise/set times were off by 30 minutes if the timezone has a 30 minutes offset. This was probably caused by some refactoring after unifying all API controller endpoints
> fix: sunrise/set times for half-hour timezones

- Sources/App/Helper/ForecastapiQuery.swift
- Tests/AppTests/ApiTests.swift
- Tests/AppTests/ZensunTests.swift
If forecast_hours is set, the default is to start from the current hour. With `initial_hours`, a different hour of the day can be selected
E.g. initial_hours=0 and forecast_hours=12 would return the first 12 hours of the current day.
> feat: Select initial hour if using forecast_hours

- Sources/App/Gfs/GfsDownload.swift
Raw model data contains -1, 101 or 102%
> fix: limit cloud cover in GFS ensemble to 0-100%.

- Sources/App/Helper/Solar/SunRiseSet.swift
- Tests/AppTests/ZensunTests.swift
Current behaviour:
- `1970-01-01T00:00` for sunset/rise for polar day and night
New behaviour:
- polar night: rise `2024-06-12T00:00` set `2024-06-12T00:00` -> 0 seconds
- polar day: rise `2024-06-12T00:00` set `2024-06-13T00:00` -> 24*3600 seconds
> fix: In case of polar day/night use 0-0h or 0-24h local time

- Sources/App/Helper/Download/Curl+Grib.swift
- Sources/App/Helper/InterpolationInplace.swift
- Sources/App/Helper/Writer/GenericVariableHandle.swift
- Sources/App/MeteoFrance/MeteoFranceDomain.swift
- Sources/App/MeteoFrance/MeteoFranceDownloader.swift
- Sources/App/configure.swift
- Tests/AppTests/ArrayTests.swift
MeteoFrance changed the API again removing some variables. They introduced a new/old package based API to get larger GRIB files that contain all variables like solar radiation and pressure level data again.
The following APIs need to be enabled for en API key:
- https://portail-api.meteofrance.fr/web/en/api/PaquetAROME
- https://portail-api.meteofrance.fr/web/en/api/PaquetARPEGE
Docs:
- AROME: https://donneespubliques.meteofrance.fr/client/document/descriptiontechnique_paquetsarome_donneespubliques_v2_20240402_367.pdf
- ARPEGE: https://donneespubliques.meteofrance.fr/client/document/descriptiontechnique_paquetsarpege_donneespubliques_v2_20240402_368.pdf
fixes #871
> New MeteoFrance API to access GRIB files as packages again

- README.md
The package now supported FlatBuffer as the main method for requesting Open Meteo's API with all features supported. Example:
```dart
import 'package:open_meteo/models/weather.dart';
import 'package:open_meteo/open_meteo.dart';
void main() async {
Weather weather = Weather(
latitude: 52.52,
longitude: 13.41,
temperature_unit: TemperatureUnit.celsius,
);
WeatherResponse result = await weather.request(
current: [Current.temperature_2m],
);
WeatherParameterData temperature =
result.currentWeatherData![Current.temperature_2m]!;
double currentTemperature = temperature.data.values.first;
print(currentTemperature);
}
```
The request URL used in the example:
```
https://api.open-meteo.com/v1/forecast?current=temperature_2m&temperature_unit=celsius&latitude=52.52&longitude=13.41&timeformat=unixtime …
```
> Add Dart client SDK to list

- Sources/App/Knmi/KnmiReader.swift
The legacy name `windspeed_10m` was wrongly mapped to 100m
> fix: 10m windspeed mapping in knmi

- Sources/App/Knmi/KnmiReader.swift
Showers in KNMI Harmonie model were bound to 0 accidentally
> fix: KNMI showers calculation

- Sources/App/Cams/CamsController.swift
- Sources/App/Controllers/EnsembleController.swift
- Sources/App/Controllers/ForecastapiController.swift
- Sources/App/Helper/Aggregation.swift
- Sources/App/Helper/ForecastapiQuery.swift
- Sources/App/Helper/Reader/GenericReader.swift
- Sources/App/Helper/Reader/GenericReaderMixerRaw.swift
- Sources/App/Helper/Reader/GenericReaderMulti.swift
- Sources/App/Helper/Writer/ForecastapiResult.swift
- Sources/App/IconWave/IconWaveController.swift
Expose a `&temporal_resolution=` parameter with options:
- `hourly` (default): Always interpolate to 1 hourly data
- `hourly_3`: Return 3-hourly data. If required aggregate data from 1-hourly to 6-hourly
- `hourly_6`: Aggregate to 6-hourly time steps
- `native`: Use the native temporal resolution of the selected weather model. If multiple models are selected with different resolutions, this will throw an error in most cases. Only the FlatBuffers format can return multiple models with different resolutions.
Closes: https://github.com/open-meteo/open-meteo/issues/556
This also closes https://github.com/open-meteo/open-meteo/issues/423, because 15-minutely data is now directly used and aggregated to 1-hourly data removing some unnecessary workarounds.
Aggregation depends in the specific …
> feat: Adjustable temporal resolution and data aggregation support

- Sources/App/Arpae/ArpaeDownloader.swift
- Sources/App/Bom/BomDownloader.swift
- Sources/App/CMA/CmaDownloader.swift
- Sources/App/Cams/CamsDownload.swift
- Sources/App/Dmi/DmiDownloader.swift
- Sources/App/Ecmwf/DownloadEcmwfCommand.swift
- Sources/App/Era5/DownloadEra5Command.swift
- Sources/App/Gem/GemDownloader.swift
- Sources/App/Gfs/GfsDownload.swift
- Sources/App/Gfs/PrecipitationProbability.swift
- Sources/App/GfsGraphCast/GfsGraphCastDownload.swift
- Sources/App/GloFas/GloFasDownloader.swift
- Sources/App/Helper/Aggregation.swift
- Sources/App/Helper/InterpolationInplace.swift
- Sources/App/Helper/OmFile.swift
- Sources/App/Helper/Reader/GenericReader.swift
- Sources/App/Helper/Writer/GenericVariableHandle.swift
- Sources/App/Icon/DownloadIconCommand.swift
- Sources/App/IconWave/IconWaveDownload.swift
- Sources/App/JMA/JmaDownloader.swift
- Sources/App/Knmi/KnmiDownloader.swift
- Sources/App/MetNo/MetNoDownloader.swift
- Sources/App/MeteoFrance/MeteoFranceDownloader.swift
- Sources/App/MfWave/MfWaveDownload.swift
- Sources/App/SeasonalForecast/SeasonalForecastDownload.swift
- Sources/App/UKMO/UkmoDownloader.swift
- Tests/AppTests/ArrayTests.swift
- Tests/AppTests/ZensunTests.swift
Automatically detects initial missing data in interpolation like `--DDDDD--D--D--D` and interpolates correctly to `--DDDDDddDddDddD` ( `-` = missing, `D` = data, `d` = interpolated)
Also detect data spacing like `--D--D--D` and interpolates to `ddDDddDDddD`
Removes all skipHour0 attributes, which are not required anymore for data conversion
> fix: Auto detect spacing in interpolation

- Sources/App/Commands/MigrationCommand.swift
- Sources/App/Controllers/ForecastapiController.swift
- Sources/App/Gfs/GfsDomain.swift
- Sources/App/Gfs/GfsDownload.swift
- Sources/App/Gfs/GfsVariable.swift
- Sources/App/Gfs/GfsVariableDownloadable.swift
- Sources/App/Gfs/PrecipitationProbability.swift
- Sources/App/Helper/DomainRegistry.swift
- docs/cronjobs.md
Precipitation probabilities are now calculated while downloading ensemble models. The old work around to calculate precipitation probabilities is not required anymore
With this change the model [`ncep_gefs025_probability`](https://openmeteo.s3.amazonaws.com/index.html#data/ncep_gefs025_probability/) is not updated anymore. Instead the models [`bom_access_global_ensemble`](https://openmeteo.s3.amazonaws.com/index.html#data/bom_access_global_ensemble/), [`cmc_gem_geps`](https://openmeteo.s3.amazonaws.com/index.html#data/), [`ecmwf_ifs025_ensemble`](https://openmeteo.s3.amazonaws.com/index.html#data/ecmwf_ifs025_ensemble/), [`dwd_icon_d2_eps`](https://openmeteo.s3.amazonaws.com/index.html#data/ecmwf_ifs025_ensemble/), [`dwd_icon_eu_eps`](https://openmeteo.s3.amazonaws.com/index.html#data/dwd_ …
> Remove old GFS precipitation probability calculation

- Sources/App/Controllers/EnsembleController.swift
ICON D2 EPS has been excluded, because it only provides 20 members and noticeable different results compared to ICON EU EPS.
See: https://github.com/open-meteo/open-meteo/issues/876
> Remove ICON D2 EPS from ICON seamless domain

- Sources/App/SeasonalForecast/SeasonalForecastDomains.swift
seasonal forecasts use 1° resolution. It does no make sense to use neighbouring grid cell. Only use nearest neighbour
> fix: NCEP cfsv2 limit search radius

- Package.swift
- Sources/App/Controllers/ForecastapiController.swift
- Sources/App/Gfs/GfsController.swift
- Sources/App/Gfs/GfsVariable.swift
- Sources/App/Gfs/GfsVariableDownloadable.swift
- Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
mass_density_8m is smoke concentration, native grib units of kg/m³ but converted to µg/m³ here for compatibility with existing Unit of microgramsPerCubicMetre
anticipating Sdk version 1.15.0 to include mass_density -> massDensity mapping for api
re proposed: https://github.com/open-meteo/open-meteo/issues/1013
> feat: add mass_density_8m variable, on ncep_hrrr model for smoke concentration

- Sources/App/Helper/Download/Curl.swift
- Sources/App/Helper/Download/HttpClient+Retry.swift
This fixes the exponential backoff delay to apply the computed delay between retries and updates the attempt counter on each retry, re: https://github.com/open-meteo/open-meteo/issues/1019
This changes 401 HTTP credential failure errors into a fatal error, with no retries. And logs an error message suggesting the credentials may be outdated.
Example	log, since CDS-beta requires all CDS users to get a brand new API key (uuid4 format now, no colon). re: https://confluence.ecmwf.int/x/uINmFw
```
% openmeteo-api download-era5 era5_land --cdskey FAIL --only-variables temperature_2m,dew_point_2m --timeinterval 20240905-20240906
[ INFO ] Downloading timerange 2024-09-05 to 2024-09-06
[ INFO ] Downloading timestamp 20240905
[ INFO ] Download failed with 401 Unauthorized error, credentials …
```
> fix: exponential backoff delay bug, and treat 401 Unauthorized as fatal

- Sources/App/Controllers/ForecastapiController.swift
- Sources/App/Era5/Era5Controller.swift
- Sources/App/Era5/Era5Variables.swift
- Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
Properly consider error propagation for spread calculation for wind speed and direction
See:
- https://en.wikipedia.org/wiki/Propagation_of_uncertainty
- speed: [WolframAlpha](https://www.wolframalpha.com/input?i=Simplify%5BSqrt%5BFold%5B%231%2B%232+%26%2CD%5B%5B%2F%2Fmath%3Aatan2%28U%2CV%29*180%2FPI+%2B+180%2F%2F%5D%2C%7B%7B%5B%2F%2Fmath%3AU%2CV%2F%2F%5D%7D%7D%5D%5E2*%7B%5B%2F%2Fmath%3Au%2Cv%2F%2F%5D%7D%5E2%5D%5D%5D)
- direction: [WolframAlpha](https://www.wolframalpha.com/input?i=Simplify%5BSqrt%5BFold%5B%231%2B%232+%26%2CD%5B%5B%2F%2Fmath%3Asqrt%28U*U%2BV*V%29%2F%2F%5D%2C%7B%7B%5B%2F%2Fmath%3AU%2CV%2F%2F%5D%7D%7D%5D%5E2*%7B%5B%2F%2Fmath%3Au%2Cv%2F%2F%5D%7D%5E2%5D%5D%5D)
> fix: ERA5 wind spread calculation

- Sources/OmFileFormatC/src/bitutil.c
- Sources/OmFileFormatC/src/fp.c
- Sources/OmFileFormatC/src/om_decoder.c
Compiling with `-Wincompatible-pointer-types` indicated these small changes.
> fix: incompatible pointer types

- Sources/OmFileFormatC/src/om_common.c
- Tests/OmFileFormatTests/OmFileFormatTests.swift
Small fix for `p4nzdec256logarithmic` compression and minor spelling fixes.
Not sure whether the test is really useful like this or if it is better to remove it and test the different compression methods in a consistent way using the om-reader-writer. 
If only the copy-round-triping should be tested (as in the current test) it might be useful to extended the test to also verify any other round-trips work as expected.
> fix log10 copying

- Sources/App/Icon/Cdo.swift
- Sources/App/Icon/DownloadIconCommand.swift
- Sources/App/Icon/Icon.swift
- Sources/App/Icon/IconVariable.swift
- Sources/App/Icon/IconVariableDownloadable.swift
I was recently building a small meteogram targeted at hobby pilots mostly paragliders and hangliders: https://terraputix.github.io/meteo-fly/?lat=36.89363&lon=-5.41386&day=1&model=icon_seamless, and would like to add estimates of convective cloud base height. This variable is directly available from icon models, so I took the freedom to open this PR to add it. 
This PR adds convective cloud base and cloud top variables for ICON models. They are available for `icon`, `icon-eu` and `icon-d2`, however `icon-d2` has shallow convection while `icon-eu` and `icon` have "deep" convection. I am honestly not sure if we can just unify them like done in this PR (most likely it matches in some cases, but in other cases the results might be rather different). What's your take on that?
Unfortunately, I …
> feat: Add ICON convective cloud base and cloud top variables

- Sources/App/Commands/ConvertOmCommand.swift
- Sources/App/Helper/NumberExtensions.swift
This fix addresses https://github.com/open-meteo/open-data/issues/24. There the conversion to netcdf with the new file format and particularly with more than 2 dimensions failed.  
This PR removes the `nx` option from the command and instead makes conversions more explicit using the `domain` option. I did it that way, because it seemed most consistent with how the om version 2 to om version 3 conversion was already implemented. 
Additionally, converting files from om2 to om3 will now need to set the additional option `format` to be `om3`, the default conversion is to `netcdf`.
> fix: om v3 file format to netcdf conversion

- Sources/App/Helper/ForecastapiQuery.swift
Closes https://github.com/open-meteo/open-meteo/issues/1236.
According to [Wikipedia](https://en.wikipedia.org/wiki/Time_in_Kazakhstan#IANA_time_zone_database):
> According to an email on the tz mailing list, Qostanay Region could be part of Asia/Qyzylorda.
And according to [release notes of tzdata 2024a](https://mm.icann.org/pipermail/tz-announce/2024-February/000081.html) the unification of kazakhstans timezone are relevant for the two modified timezones.
> fix: Asia/Qostanay timezone

- README.md
Thank you very much for this service.
We are happy to announce the integration as an addtional weather service into the OpenKNX (a project for building open and compatible knx applications and devices) Internet-Weather-Module and are planning to use it as the default source in the future, as we like the free access for typical non-commercial users.
It's important for us to comply with your terms of service, so please confirm our implementation match your expectations.
The number of API-calls of each knx-device (installed at the user) using this module and open-meteo as service is expected be far below 10K per day, so the typical smart-home-enthusiast usage (in the meaning of "Utilizing our service for personal home automation purposes.") should be within the requirements for Free-API.
* …
> Add Usage of OpenKNX OFM-InternetWeatherModule

- Sources/App/Helper/ForecastapiQuery.swift
I know explicitly decoding the `ApiQueryParameter` is bit annoying , but not explicitly handling any non optional value during decode requires people sending POST requests to specify all the non optional parameters correctly.
An alternative would be to use [MetaCodable](https://github.com/SwiftyLab/MetaCodable), but I did not want to introduce an extra dependency.
> fix: Decoding in ApiQueryParameter for POST requests

- README.md
Open Meteo is a commonly used weather integration part of the home assistant core product. It is proposed to make Open Meteo the global default weather integration of Home Assistant.
> Add home assistant to README.md

- docs/cronjobs.md
Open-data IFS025 is now one hour earlier. 
- 0/12z runs are available with a 7:40 delay
- 6/18z runs have a 7:00 delay
- This is a **one hour delay** compared to the regular dissemination schedule
For reference, Open-Meteo use the IFS HRES pre-delivery channel which can be as low as 5:45 delay.
> fix: Adjust ECMWF IFS025 Timing
