open-meteo/open-meteo

README.md

Captain Cold is a small weekend project I built that uses Open-Meteo.

Add Captain Cold

---

README.md

python api wrapper (wrote couple of months ago)

api wrapper

---

README.md
Resources/Views/docs.leaf

Some typos has been corrected in README and weather API docs.

Docs fixes

---

README.md

Such a blessing that you make this API available for open-source projects. Thanks a lot for this!
I utilized it in a small rust project that can be added to the readme if you like.

add wthrr as project that utilizes open-meteo

---

README.md

Thank you for this awesome API!

Added my own repository, Weather-Cli

---

README.md

Hello!
Very nice API. I don't regret one second since I switched to Open-Meteo. 😁 
I've been using this API for quite a while so I decided to publish a dotnet API. I hope my SDK can contribute to the project.
Greetings

added my .Net SDK - open-meteo-dotnet

---

Sources/App/Commands/CronjobCommand.swift
Sources/App/Ecmwf/DownloadEcmwfCommand.swift
Sources/App/Gfs/GfsVariableDownloadable.swift
Sources/App/Helper/Array.swift
Sources/App/Helper/Array2D.swift
Sources/App/Helper/Curl.swift
Sources/App/MeteoFrance/MeteoFranceDomain.swift
Sources/App/MeteoFrance/MeteoFranceDownloader.swift
Sources/App/MeteoFrance/MeteoFranceVariableDownloadable.swift
Sources/App/configure.swift
Tests/AppTests/DomainTests.swift

Add MeteoFrance models
This only includes a first version downloader to start storing data

MeteoFrance Arome and Arpege preliminary downloader

---

Resources/Views/docs.leaf
Sources/App/Commands/CronjobCommand.swift
Sources/App/Controllers/ForecastapiController.swift
Sources/App/Domains/LambertConformalGrid.swift
Sources/App/Gfs/GfsDomain.swift
Sources/App/Helper/Meteorology.swift
Sources/App/Helper/MultiDomainMixer.swift
Sources/App/MetNo/MetNoController.swift
Sources/App/MetNo/MetNoDomain.swift
Sources/App/MetNo/MetNoDownloader.swift
Sources/App/configure.swift
Tests/AppTests/DataTests.swift

https://github.com/metno/NWPdocs/wiki/MET-Nordic-dataset
closes #151

Integrate Met.no Nordic post processing dataset

---

README.md

Many thanks for providing Open-Meteo, I used it to make a Raycast extension, so I submitted a PR to update the `Who is using Open-Meteo?` section of the README

Update README-Who is using Open-Meteo?

---

README.md

Updated README.md with a new app

Added Slideshow app to "Who is using Open-Meteo"

---

Dockerfile

reference file .resources file directly, as the wildcard does not match

---

README.md

add R SDK to readme

---

README.md

Hi,
Great work with your library.
I made a SDK for Symfony 6.2 :)
If I have time, i'll try to make a PHP SDK which can be use for all PHP frameworks (in my opinion, there will be little changes to do to make it work without Symfony).
Feel free to test it and make me return if there are errors, it is my first package :)

Symfony sdk

---

README.md

I created another Android app. Will be published on F-Droid soon.
This app takes direct and diffuse radiation data from Open-Meteo.com, calculates the position
of the sun and projects the radiation on your solar panel.
It shows the estimated energy production for the next hours and up to 16 days.

Add solXpect Android app

---

README.md

Adding a link to this [repo](https://github.com/vnegi10/WeatherReport.jl), which is a CLI written in Julia.

Add repo link to README

---

Sources/App/MeteoFrance/MeteoFranceDownloader.swift
Sources/App/MeteoFrance/MeteoFranceVariableDownloadable.swift

Arome HD grib file contains UGUST and VGUST
```
1:0:d=2023041600:UGRD:10 m above ground:1 hour fcst:
2:3557728:d=2023041600:VGRD:10 m above ground:1 hour fcst:
3:7028613:d=2023041600:UGUST:10 m above ground:0-1 hour max fcst:
4:11034244:d=2023041600:VGUST:10 m above ground:0-1 hour max fcst:
5:14813752:d=2023041600:TMP:2 m above ground:1 hour fcst:
6:20123533:d=2023041600:RH:2 m above ground:1 hour fcst:
```
Use it to calculate gust speeds
@jortaca fyi

Add wind gusts for MeteoFrance Arome HD

---

Sources/App/Cmip6/CmipController.swift
Sources/App/Controllers/EnsembleController.swift
Sources/App/Controllers/ForecastapiController.swift
Sources/App/Ecmwf/EcmwfController.swift
Sources/App/Era5/DownloadEra5Command.swift
Sources/App/Era5/Era5Controller.swift
Sources/App/Gem/GemController.swift
Sources/App/Gfs/GfsController.swift
Sources/App/GloFas/GloFasController.swift
Sources/App/Helper/SiUnit.swift
Sources/App/Icon/IconController.swift
Sources/App/IconWave/IconWaveController.swift
Sources/App/JMA/JmaController.swift
Sources/App/MetNo/MetNoController.swift
Sources/App/MeteoFrance/MeteoFranceController.swift
Sources/App/SeasonalForecast/SeasonalForecastController.swift

Add new url parameter "length_unit" to select imperial length units for marine weather api

marine weather api "length_unit" to select imperial length units

---

README.md

Also removed trailing whitespace from README.

Add clima to list of apps using Open-Meteo

---

README.md

Add SkyMuse to apps list

---

build/openmeteo-api.service
build/openmeteo-api2.service
build/openmeteo-api3.service
build/openmeteo-notify@.service
build/openmeteo-sync.service

Replace multi-user.target by default.target to fix error in systemctl --user mode #426

Replace multi-user.target by default.target

---

Sources/App/Commands/CronjobCommand.swift
Sources/App/Controllers/ForecastapiController.swift
Sources/App/Gfs/GfsController.swift
Sources/App/Gfs/GfsDomain.swift
Sources/App/Gfs/GfsDownload.swift
Sources/App/Gfs/GfsVariableDownloadable.swift
Sources/App/Helper/Zensun.swift

Download HRRR 15min data from sub hourly GRIB files. See https://nomads.ncep.noaa.gov/pub/data/nccf/com/hrrr/prod/
TODO:

Integrate 15 minutes HRRR data

---

docs/getting-started.md

This pull requets updates the docs/getting-started.md file, in which the documentation for "deployment" lifes in.
- Change `--help` output
- Change DWD Icon domains to table view
- Fixed typographical errors
- Change `ubuntu jammy` to `Ubuntu Jammy Jellyfish`
- Change `arm` to `Arm®` to reflect their trademark guidelines https://www.arm.com/company/policies/trademarks/guidelines-trademarks
- Change `NGINX` to `nginx`
- Add Intel® AVX2 to CPU Hardware requirements

Change elements and format - Update getting-started.md

---

README.md

I hope I did it right! Your project it is amazing keep it up!

Added WetBulb to the app list

---

Sources/App/Controllers/ForecastapiController.swift
Sources/App/configure.swift

Fix https://github.com/open-meteo/open-meteo/issues/526

fix: CORS preflight support

---

Package.resolved
Package.swift
Sources/App/Cams/CamsDomain.swift
Sources/App/Cmip6/CmipDownloader.swift
Sources/App/Controllers/ForecastapiController.swift
Sources/App/Ecmwf/EcmwfDomain.swift
Sources/App/Era5/DownloadEra5Command.swift
Sources/App/Gem/GemDomain.swift
Sources/App/Gfs/GfsDomain.swift
Sources/App/Gfs/GfsDownload.swift
Sources/App/Gfs/GfsVariable.swift
Sources/App/Gfs/GfsVariableDownloadable.swift
Sources/App/GloFas/GloFasDownloader.swift
Sources/App/Helper/Download/Curl.swift
Sources/App/Helper/Download/CurlIndexed.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
Sources/App/Helper/Intrinsics/Concurrency.swift
Sources/App/Helper/Time/Time.swift
Sources/App/Icon/Icon.swift
Sources/App/IconWave/IconWaveDomain.swift
Sources/App/JMA/JmaDownloader.swift
Sources/App/MetNo/MetNoDomain.swift
Sources/App/MeteoFrance/MeteoFranceDomain.swift
Sources/App/MeteoFrance/MeteoFranceDownloader.swift
Sources/App/Satellite/SatelliteDownloader.swift
Sources/App/SeasonalForecast/SeasonalForecastDomains.swift
Sources/App/configure.swift

- Support for all GFS and HRRR levels. 
- Add convective inhibition (https://github.com/open-meteo/open-meteo/issues/339).
- Option to download past GFS and HRRR data from AWS
- Option for parallel data conversion

feat: Integrate additional layers for GFS and HRRR

---

Sources/App/Controllers/ForecastapiController.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/Download/Curl.swift
Sources/App/MeteoFrance/MeteoFranceDomain.swift
Sources/App/MeteoFrance/MeteoFranceDownloader.swift
Sources/App/MeteoFrance/MeteoFranceVariableDownloadable.swift

Add 15minutely data from MeteoFrance AROME nowcasting with 1-hourly updates

Feat: Add MeteoFrance AROME 15 minutely data

---

Sources/App/Arpae/ArpaeDownloader.swift
Sources/App/CMA/CmaDownloader.swift
Sources/App/Gem/GemDownloader.swift
Sources/App/Gfs/GfsDownload.swift
Sources/App/Helper/Writer/GenericVariableHandle.swift
Sources/App/Icon/DownloadIconCommand.swift
Sources/App/JMA/JmaDownloader.swift
Sources/App/configure.swift

Refactor code, use multipart downloads and concurrent processing
Concurrent processing is especially helpful to process pressure level data. As all processing steps are not on dedicated servers, more CPU cores are available to parallel processing.

Upgrade JMA, GEM, DWD downloader

---

README.md

Let me know if you want any change

Add OSS Weather App to using

---

Sources/App/Controllers/EnsembleController.swift
Sources/App/Controllers/ForecastapiController.swift
Sources/App/Ecmwf/DownloadEcmwfCommand.swift
Sources/App/Ecmwf/EcmwfReader.swift
Sources/App/Ecmwf/EcmwfVariable.swift
Sources/App/Helper/Array.swift

new variables released:
- 100m wind
- shortwave radiation
- soil moisture 0-7 and 7-28 cm depth
- cape

IFS 025° additional weather variables

---

Package.resolved
Package.swift
Sources/App/Gem/GemDownloader.swift
Sources/App/Gfs/GfsDownload.swift
Sources/App/Helper/WeatherCode.swift
Sources/App/Helper/Writer/GenericVariableHandle.swift
Sources/App/Icon/Cdo.swift
Sources/App/Icon/DownloadIconCommand.swift
Sources/App/Icon/IconReader.swift
Sources/App/Icon/IconVariable.swift

ICON generates snowfall even if the snowfall height is >500 metres above ground at 5-10°C. This PR converts snow back to liquid rain.

fix: Correct ICON snowfall amount if snowfall height is significantly higher than terrain

---

Sources/App/GfsGraphCast/GfsGraphCastDomain.swift
Sources/App/GfsGraphCast/GfsGraphCastDownload.swift

See: https://github.com/NOAA-EMC/graphcast/issues/39

Switch GFS GraphCast to 13 pressure levels

---

Sources/App/Arpae/ArpaeDownloader.swift
Sources/App/Bom/BomDomain.swift
Sources/App/Bom/BomDownloader.swift
Sources/App/CMA/CmaDownloader.swift
Sources/App/Commands/SyncCommand.swift
Sources/App/Controllers/ForecastapiController.swift
Sources/App/Ecmwf/DownloadEcmwfCommand.swift
Sources/App/Gem/GemDownloader.swift
Sources/App/Gfs/GfsDownload.swift
Sources/App/Gfs/PrecipitationProbability.swift
Sources/App/GfsGraphCast/GfsGraphCastDownload.swift
Sources/App/Helper/Writer/GenericVariableHandle.swift
Sources/App/Icon/DownloadIconCommand.swift
Sources/App/JMA/JmaDownloader.swift
Sources/App/MeteoFrance/MeteoFranceDownloader.swift

`Precipitation probabilities` are only calculated from GEFS in 0.25° using 31 members for up to 10 days. This may lead to inconsistencies because other models like ICON may be used.
This PR extends processing for all ensemble models to generate precipitation probability fields by analysing all members for precipitation > 0.1 mm/h. 
Upon fetching precipitation probability through the regular [Open-Meteo weather forecast API](https://open-meteo.com/en/docs), the API will select the most suitable ensemble domain. E.g. ICON for Europe or GEFS for North America. If model like `gem_global`, `ecmwf_ifs025 ` or `bom_access_global` are selected manually in the weather models dropdown, precipitation probability is used from the appropriate ensemble model `GEM ensemble`, `IFS0.25° ensemble` or `BOM …

feat: Use diagnostic precipitation probability from all ensemble domains

---

Package.resolved
Package.swift
Sources/App/Ecmwf/DownloadEcmwfCommand.swift
Sources/App/Ecmwf/EcmwfDomain.swift
Sources/App/Ecmwf/EcmwfVariable.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+MarineApi.swift
Sources/App/IconWave/IconWaveController.swift

Currently ICON GWAM model is not updated anymore. Implement ECMWF WAM 0.25° as a replacement

Integrate ECMWF WAM 0.25° model

---

Sources/App/GloFas/GloFasDownloader.swift

Instead of 1x 220GB GRIB file, it is now split in 51x 4.3GB files. Note: Some of the optimisations to work with 220GB files could now be removed.

fix: New GloFas URL format for seasonal forecast

---

README.md

Adds MeteoHist App to the list of Apps in the Readme file.

Add MeteoHist App

---

Sources/App/Domains/GaussianGrid.swift
Sources/App/Domains/Gridable.swift
Sources/App/Domains/ProjectionGrid.swift
Sources/App/Domains/RegularGrid.swift
Sources/App/MfWave/MfWaveDomain.swift
Tests/AppTests/DataTests.swift

Extend the grid-cell search radius to ~16 km (5x5 block)

fix: meteofrance wave model has no data close to shore

---

Package.resolved
Package.swift
Sources/App/Controllers/ForecastapiController.swift
Sources/App/Dmi/DmiDomain.swift
Sources/App/Dmi/DmiDownloader.swift
Sources/App/Dmi/DmiReader.swift
Sources/App/Dmi/DmiVariable.swift
Sources/App/Domains/DebugFromGRIB.swift
Sources/App/Domains/LambertConformalConic.swift
Sources/App/Domains/ProjectionGrid.swift
Sources/App/Gfs/GfsDomain.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/Download/Curl+Grib.swift
Sources/App/Helper/Download/Curl.swift
Sources/App/Helper/Download/GribStream.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
Sources/App/Helper/Time/Time.swift
Sources/App/Helper/Writer/GenericVariableHandle.swift
Sources/App/Knmi/KnmiDomain.swift
Sources/App/Knmi/KnmiDownloader.swift
Sources/App/Knmi/KnmiReader.swift
Sources/App/Knmi/KnmiVariable.swift
Sources/App/configure.swift
Sources/SwiftPFor2D/FileExtension.swift
Sources/SwiftPFor2D/SwiftPFor2D.swift
Tests/AppTests/DataTests.swift

https://dataplatform.knmi.nl/group/weather-forecast?q=UWC&sort=metadata_modified+desc

Integrate KNMI HARMONIE models

---

Sources/App/Arpae/ArpaeReader.swift
Sources/App/Ecmwf/EcmwfReader.swift
Sources/App/Ecmwf/EcmwfVariable.swift
Sources/App/Era5/Era5Controller.swift
Sources/App/Era5/Era5Domain.swift
Sources/App/GfsGraphCast/GfsGraphCastReader.swift
Sources/App/JMA/JmaController.swift

Make sure that all weather models zero out showers if they are not available

fix: Ensure consistency of sum between shower, rain, snow and precipitation

---

Sources/App/Helper/FlatBufferWriter/FlatBuffers+MarineApi.swift

Fixes https://github.com/open-meteo/open-meteo/issues/936

Fix variable typo in FlatBuffers+MarineApi.swift

---

Sources/App/Helper/FlatBufferWriter/FlatBuffers+EnsembleApi.swift

Fix typos in FlatBuffers+EnsembleApi.swift

---

Package.resolved
Package.swift
Sources/App/Cams/CamsController.swift
Sources/App/Controllers/EnsembleController.swift
Sources/App/Controllers/ForecastapiController.swift
Sources/App/Domains/LambertAzimuthalEqualAreaProjection.swift
Sources/App/Domains/ProjectionGrid.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/Download/Curl.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+AirQualityApi.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+ClimateApi.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+EnsembleApi.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+FloodApi.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+MarineApi.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+SeasonalApi.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
Sources/App/Helper/Meteorology.swift
Sources/App/Helper/PressureVariableRespresentable.swift
Sources/App/Helper/Time/Time.swift
Sources/App/Helper/Writer/ForecastapiResult.swift
Sources/App/UKMO/UkmoDomain.swift
Sources/App/UKMO/UkmoDownloader.swift
Sources/App/UKMO/UkmoReader.swift
Sources/App/UKMO/UkmoVariable.swift
Sources/App/configure.swift
Tests/AppTests/DataTests.swift
Tests/AppTests/OutputformatTests.swift
Tests/AppTests/ZensunTests.swift
docs/cronjobs.md

Preview is available here: https://ukmo.open-meteo-website.pages.dev/en/docs/ukmo-api#latitude=51.5085&longitude=-0.1257&past_days=3&models=ukmo_global_deterministic_10km,ukmo_uk_deterministic_2km

feat: Integrate UKMO global 10km and 2km uk models

---

Sources/App/Gem/GemDownloader.swift

Precipitation probability was not calculated for CMC GEM models

fix: GEM ensemble model precipitation probability calculation

---

Sources/App/Gfs/GfsDomain.swift

See: https://nomads.ncep.noaa.gov/pub/data/nccf/com/gens/prod/gefs.20240828/18/atmos/pgrb2sp25/

GFS ensemble025 got shortened to forecasthour 240

---

Sources/App/Era5/Era5Variables.swift

Looks like a merge removed CDS wave variables names

fix: era5 ocean download

---

Sources/App/Controllers/ForecastapiController.swift
Sources/App/Era5/DownloadEra5Command.swift
Sources/App/Era5/Era5Variables.swift
Sources/App/Gfs/GfsVariable.swift
Sources/App/Gfs/GfsVariableDownloadable.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift

Add PBL height and total column water vapour to GFS, ECMWF IFS and ERA5

feat: Add PBL height and total column vapour

---

Sources/App/Era5/DownloadEra5Command.swift
Sources/App/UKMO/UkmoDownloader.swift

Manually converted from GRIB files

feat: UKMO global elevation and LSM data

---

Sources/App/MeteoFrance/MeteoFranceDownloader.swift
Sources/App/MeteoFrance/MeteoFranceVariableDownloadable.swift

See https://github.com/open-meteo/open-meteo/discussions/1033#discussioncomment-10818311

fix wind gusts in AROME 0.01 PI, add shortwave radiation to PI and clouds

---

README.md

added my repository to the list of your API users and as an embedded C++ implementation example.

Update README.md, added esp8266-weather-station

---

Package.resolved
Package.swift
Sources/App/Controllers/ForecastapiController.swift
Sources/App/Gfs/GfsDownload.swift
Sources/App/Gfs/PrecipitationProbability.swift
Sources/App/GloFas/GloFasDownloader.swift
Sources/App/Helper/Array2D.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/Download/CurlIndexed.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+MarineApi.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
Sources/App/Nbm/NbmController.swift
Sources/App/Nbm/NbmDomain.swift
Sources/App/Nbm/NbmDownload.swift
Sources/App/Nbm/NbmVariable.swift
Sources/App/Nbm/NbmVariableDownloadable.swift
Sources/App/configure.swift
Tests/AppTests/DataTests.swift
docs/cronjobs.md

Updated docs: https://github.com/open-meteo/open-meteo-website/pull/334

feat: Integrate NCEP NBM models

---

Sources/App/Controllers/ForecastapiController.swift
Sources/App/Gfs/PrecipitationProbability.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/Writer/GenericVariableHandle.swift
Sources/App/MeteoFrance/MeteoFranceDomain.swift
Sources/App/MeteoFrance/MeteoFranceDownloader.swift
Sources/App/MeteoFrance/MeteoFranceVariableDownloadable.swift
docs/cronjobs.md

Adds 4 days of precipitation probability forecast for ARPEGE Europe model.

feat: MeteoFrance ARPEGE statistical ensemble forecast for precipitation probability

---

Package.resolved
Package.swift
Sources/App/Cams/CamsController.swift
Sources/App/Cams/CamsDomain.swift
Sources/App/Cams/CamsDownload.swift
Sources/App/Cams/CamsGreenhouseGases.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/Download/GribAttributes.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+AirQualityApi.swift
Sources/App/Helper/Writer/GenericVariableHandle.swift
docs/cronjobs.md

https://confluence.ecmwf.int/pages/viewpage.action?pageId=394237962
Provides global CO, CO2 and methane

feat: Integrate CAMS global greenhouse gases

---

README.md

I created a fun app to display the weather with emojis. Is it possible to add it to the list of apps?
Thanks

Add Emojiton like a app using Open-Mateo

---

Sources/App/Ecmwf/EcmwfVariable.swift
Sources/App/Helper/Download/CurlIndexed.swift

ECMWF added new soil temperature and moisture levels

feat: Add IFS open data soil temperature and moisture

---

Sources/App/Helper/NumberExtensions.swift
Sources/App/Helper/OmFile.swift
Sources/App/UKMO/UkmoDownloader.swift
Sources/App/UKMO/UkmoReader.swift
Sources/App/UKMO/UkmoVariable.swift

Data is provided as instantaneous data. Convert to backwards averaged data.

fix: UK Met Office global solar radiation

---

Sources/App/Ecmwf/EcmwfDomain.swift
Sources/App/Ecmwf/EcmwfReader.swift
Sources/App/Ecmwf/EcmwfVariable.swift

Also adds precipitation type which is now used for snow

Extend IFS open data forecast length from 10 to 15 days

---

README.md

Closes: https://github.com/open-meteo/open-meteo/issues/1102

add biome to the "Who is using Open-Meteo?" section

---

Sources/App/Controllers/ForecastapiController.swift
Sources/App/Ecmwf/DownloadEcmwfCommand.swift
Sources/App/Ecmwf/EcmwfVariable.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift

- Fix hour 0 in wind gusts
- Add min/max 3h temperature
- Add precipitation type to output

feat: Additional variables in ECMWF IFS0.25° open-data

---

Sources/App/Gfs/GfsController.swift
Sources/App/Gfs/GfsDownload.swift
Sources/App/Gfs/GfsVariable.swift

calculate snowfall amount while downloading instead of using fro…zen precip in percent. Fixes archiving issues, because forecast hour 0 is always 0% snowfall.

fix: Snowfall archiving in NOAA HRRR. Process snowfall amount while downloading.

---

Sources/App/Controllers/EnsembleController.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+EnsembleApi.swift
Sources/App/Helper/Time/Time.swift
Sources/App/UKMO/UkmoDomain.swift
Sources/App/UKMO/UkmoDownloader.swift
Sources/App/UKMO/UkmoVariable.swift

Issues:
- No total precipitation data

feat: Integrate UK Met Office global ensemble forecasts

---

Package.resolved
Package.swift
Sources/App/Controllers/WebsiteController.swift
Sources/App/Helper/OmFile.swift
build/openmeteo-api.service
build/openmeteo-api2.service
build/openmeteo-api3.service
build/openmeteo-sync.service

Reads on most eastern edge may cause issues

fix: Rare API crashes with new file format on domain borders

---

Sources/App/Controllers/ForecastapiController.swift
Sources/App/Era5/DownloadEra5Command.swift
Sources/App/EumetsatSarah/EumetsatSarahDomain.swift
Sources/App/EumetsatSarah/EumetsatSarahDownloader.swift
Sources/App/EumetsatSarah/EumetsatSarahReader.swift
Sources/App/EumetsatSarah/EumetsatSarahVariable.swift
Sources/App/Helper/Array3D.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/Download/Curl.swift
Sources/App/Helper/Download/HttpClient+Retry.swift
Sources/App/Helper/Download/TimeoutTracker.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
Sources/App/Helper/OmFile.swift
Sources/App/Helper/Solar/Zensun.swift
Sources/App/Helper/Vapor/ApiKeyManager.swift
Sources/App/Helper/Writer/GenericVariableHandle.swift
Sources/App/configure.swift

Integrate SARAH-3 data
- https://wui.cmsaf.eu/safira/action/viewDoiDetails?acronym=SARAH_V003
- via EUMETSAT API https://data.eumetsat.int/data/map/EO:EUM:DAT:0863
Downloads 30 minutely shortwave and direct radiation. Original data is instantaneous, but has a scan time offset (0 minutes in the south, 20 minutes in the north). The scan time offset is applied and then converted to backwards averages. Using clearness index missing values are sunset are restored.
At later states, daylight duration might be added. However this is only a daily value and the current code structure cannot work with daily data directly.

feat: EUMETSAT SARAH-3 satellite solar radiation

---

Sources/App/Controllers/ForecastapiController.swift
Sources/App/Ecmwf/DownloadEcmwfCommand.swift
Sources/App/Ecmwf/EcmwfDomain.swift
Sources/App/Ecmwf/EcmwfReader.swift
Sources/App/Ecmwf/EcmwfVariable.swift
Sources/App/Helper/DomainRegistry.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift

https://confluence.ecmwf.int/display/FCST/Implementation+of+AIFS+Single+v1

feat: Integrate AIFS0.25° Single

---

Sources/App/Helper/Reader/GenericReaderDerived.swift

Miss leading error message.
Pls change thx!

Update azimuth max min to -180 / 180 GenericReaderDerived.swift

---

Public/docs/openapi.yml
openapi.yml
openapi_historical_weather_api.yml

Fixes #1274
Correct validation issues with openapi spec files.
You can test previous version vs new version with https://editor.swagger.io/
This shows the validation issues and also renders the spec and allows you to call the routes directly from there. Would be nice to add swagger to this repo with auto-generation as a github workflow and github pages to host it statically!

Fix OpenAPI yaml file

---

README.md

Added my weather app - alpineconditions.com - to the Readme file
Added a fork of the AlienDwarf dotnet client - I've added support for mkore models, weather variables & use of an OpenMeteoAPI Key

Add AlpineConditions & Dotnet 8 Client SDK to README

---

Sources/App/Controllers/EnsembleController.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+EnsembleApi.swift
Sources/App/Helper/GenericDailyCalculator.swift

Example: https://ensemble-api.open-meteo.com/v1/ensemble?latitude=52.52&longitude=13.41&daily=temperature_2m_max&models=icon_seamless

feat: add daily aggregation for ensemble data

---

Sources/App/Controllers/ForecastapiController.swift

Previously pastDays was always limited to 92 even for previous models runs

fix: Automatically calculate pastDaysMax based on history forecast range

---

Sources/App/Controllers/ForecastapiController.swift
Sources/App/Helper/FlatBufferWriter/FlatBuffers+WeatherApi.swift
Sources/App/JMA/JmaController.swift

Add bounding box support for all "single" domains excluding seamless domains

feat: Bound box support all domains

---

Sources/App/Commands/ExportCommand.swift
Sources/App/Helper/SiUnit.swift

Speed improvements for export command

feat: Export command use multiple threads and chunking

---

Sources/App/Helper/Writer/VariablePerMemberStorage.swift

Fix race condition in getting U/V components from temporary storage

fix: concurrent wind processing

---

Sources/App/Domains/Gridable.swift
Sources/App/Domains/RegularGrid.swift
Tests/AppTests/ApiTests.swift
Tests/AppTests/DataTests.swift
Tests/AppTests/DomainTests.swift

Closes https://github.com/open-meteo/open-meteo/issues/1474.

fix: fatal crash for bounding box queries at date line
